### PR TITLE
Fiducial fix

### PR DESCRIPTION
**Pull request by ConnyCola**
This fix should also work for any components that do not have a cream or stop layer. (Those are flags in the UL_SMD component). This implementation might still break if you have part that does not have a cream layer but still thermals for some reason.
Should fix https://github.com/Funkenjaeger/brd2json/issues/3

### CODE REVIEW

**Comment by Funkenjaeger** [comment]
Using the Fiducials library you shared, this works for the plain fiducials but not the ones with paste ("_P" suffix), since those do have the SMD_FLAG_CREAM flag set.  I changed the logic to only look for SMD_FLAG_STOP.

While I was at it, I revised the nearby logic so it will actually preserve round SMD pads (as used in these fiducials) rather than turning them into rectangles by default.

**Comment by ConnyCola** [comment]
I think the shape change you implemented might need some more work. I does the trick for circles but now rects with rounded corners show up as circles too. 
image
image

**Comment by Funkenjaeger** [comment]
Good catch.  I guess roundness=100% is a necessary but not sufficient condition - I should have also checked that dx==dy before deciding to treat it as a circle.

While I'm at it I'm going to just do what I should have done before and take the last step to support rounded rectangles fully (which could have roundness anywhere from 1% to 100%)

I think the only other pad type (of those supported in InteractiveHtmlBom) that wouldn't be covered at that point is chamfered rectangle, but that's not something I recall encountering in a footprint before.

**Comment by Funkenjaeger** [comment]
Fixed in a3ebf9db8d7eb0a27720b315bb1f6e1ab4f8d37b - I added full rounded rectangle support, so any roundness from 0 to 100 will work, and it will only turn into a circle if roundness == 100 && dx == dy.
Screenshot 2021-02-14 095020

**Pull request merged**
